### ISSUE TITLE
Use this as library instead of gulp-plugin?

### ISSUE THREAD

**Issue by pateketrueke** [Rapid-Application-Development-JS/gulp-incremental#1]
I want to use this functionality but not in gulp, it is possible?

**Comment by YLuchaninov** [comment]
Yes, it is possible to use the same approach(not a code) for the library to translate a template into an incremental DOM function. But unfortunately it will take time.

So, we will think about creating a library for compiling templates on the browser side into functions. But it will be placed in another repo in this organisation, and compiling will run during template loading, and then it will be placed in global namespace.
What do you think about it?

**Comment by MobiDevBiz** [comment]
https://github.com/Rapid-Application-Development-JS/itemplate
